name: tiledb-env
channels:
  - conda-forge
  - defaults
dependencies:
  - python>=3.6
  - Sphinx==1.6.7
  - breathe==4.7.3
  - cmake
  - bzip2>=1.0.0
  - zstd==1.3.3
  - lz4-c==1.8.0
  - blosc>=1.0.0
  - pip:
    - sphinx-tabs==1.1.7
